// <auto-generated />
using System;
using DocumentIA.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentIA.Data.Migrations
{
    [DbContext(typeof(DocumentIADbContext))]
    [Migration("20260130122543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentIA.Data.Entities.AuditoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetallesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CRC32")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double?>("ConfianzaGlobal")
                        .HasColumnType("float");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdActivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdGDC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("RutaBlobStorage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Estado");

                    b.HasIndex("SHA256")
                        .IsUnique();

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ConfianzaClasificacion")
                        .HasColumnType("float");

                    b.Property<string>("DatosExtraidosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<bool>("FallbackLLM")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InconsistenciasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LayoutEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModeloClasificacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModeloExtraccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModuloIntegracion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizacionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoIntegracion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TiempoClasificacionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoExtraccionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoIntegracionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoNormalizacionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoTotalMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoValidacionMs")
                        .HasColumnType("int");

                    b.Property<string>("ValidacionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.ToTable("ResultadosProcesamiento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.TipologiaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfiguracionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloClasificacionDI")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModeloExtraccionDI")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromptGPT")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("UmbralClasificacion")
                        .HasColumnType("float");

                    b.Property<double>("UmbralExtraccion")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tipologias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "tasacion",
                            FechaCreacion = new DateTime(2026, 1, 30, 12, 25, 42, 817, DateTimeKind.Utc).AddTicks(8190),
                            Nombre = "Tasación",
                            UmbralClasificacion = 0.84999999999999998,
                            UmbralExtraccion = 0.80000000000000004,
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.AuditoriaEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEntity", "Documento")
                        .WithMany("Auditorias")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEntity", "Documento")
                        .WithOne("Resultado")
                        .HasForeignKey("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEntity", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Resultado");
                });
#pragma warning restore 612, 618
        }
    }
}
