// <auto-generated />
using System;
using DocumentIA.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentIA.Data.Migrations
{
    [DbContext(typeof(DocumentIADbContext))]
    partial class DocumentIADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentIA.Data.Entities.AuditoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetallesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEjecucionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityTimelineJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfianzaClasificacion")
                        .HasColumnType("float");

                    b.Property<double>("ConfianzaGlobal")
                        .HasColumnType("float");

                    b.Property<string>("ContratoSalidaCompletoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosFinalesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosOriginalesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionClasificacionMs")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionExtraccionMs")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionGDCMs")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionIntegracionMs")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionPersistenciaMs")
                        .HasColumnType("int");

                    b.Property<int>("DuracionTotalMs")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionValidacionMs")
                        .HasColumnType("int");

                    b.Property<string>("EjecucionGuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EstadoFinal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloClasificacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseFallbackLLM")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("EjecucionGuid")
                        .IsUnique();

                    b.HasIndex("FechaEjecucion");

                    b.ToTable("DocumentoEjecuciones");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CRC32")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double?>("ConfianzaGlobal")
                        .HasColumnType("float");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdActivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdGDC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MD5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NormalizacionMarkdownCompressed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("RutaBlobStorage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Estado");

                    b.HasIndex("SHA256")
                        .IsUnique();

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ModeloConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConfiguracionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ModeloConfigs");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.PluginEjecucionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatosEnriquecidosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<int>("EjecucionId")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PluginKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EjecucionId", "PluginKey");

                    b.ToTable("PluginEjecuciones");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.PluginTipologiaConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfiguracionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublicadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicadaPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipologiaCodigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaCodigo")
                        .IsUnique();

                    b.ToTable("PluginTipologiaConfigs");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ConfianzaClasificacion")
                        .HasColumnType("float");

                    b.Property<string>("DatosExtraidosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<bool>("FallbackLLM")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InconsistenciasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LayoutEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModeloClasificacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModeloExtraccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModuloIntegracion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizacionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEjecucion")
                        .HasColumnType("int");

                    b.Property<double>("PorcentajeCompletitud")
                        .HasColumnType("float");

                    b.Property<string>("ResultadoIntegracion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TiempoClasificacionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoExtraccionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoIntegracionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoNormalizacionMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoTotalMs")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoValidacionMs")
                        .HasColumnType("int");

                    b.Property<int>("TotalErroresValidacion")
                        .HasColumnType("int");

                    b.Property<int>("TotalPluginsEjecutados")
                        .HasColumnType("int");

                    b.Property<int>("TotalValidacionesAplicadas")
                        .HasColumnType("int");

                    b.Property<int>("TotalWarningsValidacion")
                        .HasColumnType("int");

                    b.Property<string>("ValidacionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.ToTable("ResultadosProcesamiento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.TipologiaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfiguracionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloClasificacionDI")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModeloExtraccionDI")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromptGPT")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublicadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicadaPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("UmbralClasificacion")
                        .HasColumnType("float");

                    b.Property<double>("UmbralExtraccion")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VersionPublicada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tipologias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "tasacion",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 4, 8, 9, 30, 14, 495, DateTimeKind.Utc).AddTicks(6871),
                            Nombre = "Tasación",
                            PublicadaEn = new DateTime(2026, 4, 8, 9, 30, 14, 495, DateTimeKind.Utc).AddTicks(6865),
                            PublicadaPor = "seed",
                            UmbralClasificacion = 0.84999999999999998,
                            UmbralExtraccion = 0.80000000000000004,
                            Version = "1.0",
                            VersionPublicada = "1.0"
                        });
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ValidacionResultadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EjecucionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pasado")
                        .HasColumnType("bit");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValorEsperado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValorOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EjecucionId", "Campo");

                    b.ToTable("ValidacionResultados");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.AuditoriaEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEntity", "Documento")
                        .WithMany("Auditorias")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEjecucionEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEntity", "Documento")
                        .WithMany("Ejecuciones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.PluginEjecucionEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEjecucionEntity", "Ejecucion")
                        .WithMany("PluginsEjecutados")
                        .HasForeignKey("EjecucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejecucion");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEntity", "Documento")
                        .WithOne("Resultado")
                        .HasForeignKey("DocumentIA.Data.Entities.ResultadoProcesamientoEntity", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.ValidacionResultadoEntity", b =>
                {
                    b.HasOne("DocumentIA.Data.Entities.DocumentoEjecucionEntity", "Ejecucion")
                        .WithMany("Validaciones")
                        .HasForeignKey("EjecucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejecucion");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEjecucionEntity", b =>
                {
                    b.Navigation("PluginsEjecutados");

                    b.Navigation("Validaciones");
                });

            modelBuilder.Entity("DocumentIA.Data.Entities.DocumentoEntity", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Ejecuciones");

                    b.Navigation("Resultado");
                });
#pragma warning restore 612, 618
        }
    }
}
